### PR TITLE
Update README to be more informative

### PR DESCRIPTION
**Pull request by dadair-ca**
The README has been updated to:
- include a screenshot of the application for its intended purpose
- discuss the software's purpose
- provide updated dependency information
- provide build instructions

### CODE REVIEW

**Comment by dgobbi** [comment]
Just a reminder about screenshots: always resize the window to make it smaller.  Or, even better, switch to a display resolution that is similar to a tablet screen (non-retina).

**Comment by dadair-ca** [comment]
I'll upload a smaller screenshot and update the pull-request.

**Comment by dgobbi** [comment]
The instructions should also state that VTK 5.10 is required (VTK 6 will not work). 

ITK must be version 4.5 or later (otherwise VtkItkGlue is required).

**Comment by dadair-ca** [comment]
Updated according to your comments.

**Comment by dgobbi** [comment]
This might sound like a silly request, but can you rebase to remove the larger image from the commit history?  E.g. "rebase -i origin/master" and then edit the commit that added the original image, so that it adds the smaller one instead.

**Comment by dgobbi** [comment]
Hey, wait a minute... the new image is huge!  It took forever to load through my FMC connection.

**Comment by dadair-ca** [comment]
Should be much better now, down to 264.824 kB from 1MB.

**Comment by dgobbi** [comment]
Thanks.  I've rebased and merged.

**Pull request closed without merging**
